import Head from "next/head";
import styles from "../../styles/Header.module.css";

const Header = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Timezone search</h1>
    </>
  );
};

export default Header;
